.PHONY: run
run:
	@docker-compose up -d
	@echo "Tu ropa, damela"
	@echo "https://www.youtube.com/watch?v=NbZOb__8aBE"

.PHONY: stop
stop:
	@docker-compose down
	@echo "Hasta la vista baby"
	@echo "https://www.youtube.com/watch?v=LRxaXmXvjnU"